on: push

name: Lint

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: ludeeus/action-shellcheck@0.5.0
        env:
          SHELLCHECK_OPTS: -e SC1091,SC1117,SC2001,SC2034

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shfmt
        uses: bltavares/actions/shfmt@master
        env:
          SHFMT_ARGS: -d
